keep-open=yes
autofit=80%
volume=80
volume-max=100

alang=eng,en
slang=vi,vie,eng,en
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=3
screenshot-directory=~/Pictures/mpv
screenshot-template=%F - [%P] (%#01n)
save-position-on-quit=yes

profile=high-quality
ytdl-format=bestvideo+bestaudio
cache-default=4000000

audio-file-auto=fuzzy
autofit-larger=100%x100%
geometry=50%:50%

osd-font=JetBrainsMono Nerd Font Mono
sub-font=JetBrainsMono Nerd Font Mono
sub-auto=fuzzy
sub-color=1/1/1/1
sub-bold=yes
sub-border-style=background-box
sub-outline-size=0
sub-shadow-offset=4
sub-back-color=0/0/0/0.5
sub-pos=95
