general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = equal, 1, 0.5, 0, 0.5
    bezier = outCirc, 0.075, 0.82, 0.165, 1
    bezier = inCirc, 0.6, 0.04, 0.98, 0.335
    bezier = inOutCirc, 0.785, 0.135, 0.15, 0.86

    animation = fade, 1, 4, inCirc
    animation = inputFieldDots, 1, 2, linear
    animation = inputFieldFade, 1, 4, outCirc
    animation = inputFieldWidth, 1, 3, inOutCirc
    animation = inputFieldColors, 1, 6, linear
}

background {
    monitor =
    path = screenshot
    color = 0xFF191b1d
    blur_size = 9
    blur_passes = 3
    brightness = 0.2
}

input-field {
    monitor =
    size = 250, 40
    position = 0, -20
    fade_timeout = 500
    rounding = 0
    outline_thickness = 1

    fail_color = 0xFFcc6666
    outer_color = 0xFF969896
    inner_color = 0x00191b1d
    check_color = 0xFFb5bd68
    font_color = 0xFF81a2be
    capslock_color = 0xFFcc6666

    dots_center = true
    dots_size = 0.28
    dots_spacing = 0.10
    dots_rounding = -1
    font_family = Ubuntu Nerd Font
    placeholder_text =

    halign = center
    valign = center
}

label {
    monitor =
    position = 0, 150
    text = $TIME
    color = 0xFFb4b7b4
    font_size = 96
    font_family = Ubuntu Nerd Font

    halign = center
    valign = center
}

label {
    monitor =
    position = 0, 60
    text = cmd[update:10000] date '+%A %d %B %Y'
    color = 0xFFb4b7b4
    font_size = 24
    font_family = Ubuntu Nerd Font

    halign = center
    valign = center
}
